Bug fixes

diff --git a/.github/workflows/infrastructure-download-external.yml b/.github/workflows/infrastructure-download-external.yml
--- a/.github/workflows/infrastructure-download-external.yml
+++ b/.github/workflows/infrastructure-download-external.yml
@@ -51,8 +51,18 @@ env:
 
 jobs:
 
+  perm:
+    name: "Restore permissions"
+    runs-on: repository-sync
+    steps:
+      - name: "Restore permissions"
+        run: |
+
+          sudo chown -R ${{ secrets.HOST_UPLOAD_USER }}:${{ secrets.HOST_UPLOAD_USER }} /armbian/openssh-server/storage/{debs,debs-beta,artifacts}
+
   start:
     runs-on: ${{ inputs.BUILD_RUNNER }}
+    needs: perm
     name: "Mirror"
     outputs:
       matrix: ${{steps.lists.outputs.matrix}}
@@ -304,15 +314,12 @@ jobs:
             --keyserver keyserver.ubuntu.com \
             --recv-keys 648ACFD622F3D138 0E98404D386FA1D9
 
-      - name: "Download method: ${{ matrix.method }}"
-        id: calculate
+      - name: "Prepare machine"
+        id: preparing
         shell: bash
         run: |
-          SOURCE="temp/"
-          mkdir -p ${SOURCE}
 
           # Load configuration
-          echo "::debug::Sourcing config file: os/external/${{ matrix.name }}.conf"
           . os/external/${{ matrix.name }}.conf
 
           echo "::debug::Config loaded - URL: ${URL}, KEY: ${KEY}, INSTALL: ${INSTALL}, ARCH: ${ARCH}, RELEASE: ${RELEASE}"
@@ -327,7 +334,7 @@ jobs:
           chmod go+r /usr/share/keyrings/armbian.gpg
 
           # Add Armbian repository
-          echo "deb [arch=${{ matrix.arch }} signed-by=/usr/share/keyrings/armbian.gpg] http://apt.armbian.com ${{ matrix.release }} main ${{ matrix.release }}-utils ${{ matrix.release }}-desktop" > /etc/apt/sources.list.d/armbian-${{ matrix.release }}.list
+          echo "deb [arch=${{ matrix.arch }} signed-by=/usr/share/keyrings/armbian.gpg] http://netcup-01.armbian.com/apt ${{ matrix.release }} main ${{ matrix.release }}-utils ${{ matrix.release }}-desktop" > /etc/apt/sources.list.d/armbian-${{ matrix.release }}.list
 
           # Configure APT sources for AMD64 architecture
           sudo awk '
@@ -424,6 +431,17 @@ jobs:
           # Update package lists and get current version
           apt-get update
 
+      - name: "Download method: ${{ matrix.method }}"
+        id: calculate
+        shell: bash
+        run: |
+
+          # Load configuration
+          . os/external/${{ matrix.name }}.conf
+
+          SOURCE="temp/"
+          mkdir -p ${SOURCE}
+
           # Check installed version if exists
           PKG="${INSTALL%% *}"
           BEFORE_VERSION="$(apt-cache policy "$PKG" 2>/dev/null | awk '/Candidate:/ {print $2; exit}' | cut -d: -f2-)"
@@ -453,7 +471,7 @@ jobs:
 
             # exception
             if [[ "${{ matrix.name }}" == "haos-supervised-installer" ]]; then
-                PATTERNS+=('*.deb')
+                PATTERNS=('*.deb')
             fi
 
             echo "Downloading from GitHub release ${TAG}"
@@ -464,10 +482,27 @@ jobs:
                 --repo "${URL}" \
                 --dir "${SOURCE}" || true
             done
-            ls -l ${SOURCE}
+
+            # exception
+            if [[ "${{ matrix.name }}" == "fastfetch" ]]; then
+                rm -f "${SOURCE}"*polyfilled*
+            fi
+
+            # Check if any .deb files were downloaded
+            if ! ls "${SOURCE}"*.deb &> /dev/null; then
+              echo "::error::No .deb files were downloaded for ${{ matrix.name }} on ${{ matrix.arch }}" >&2
+              echo "Patterns tried: ${PATTERNS[*]}" >&2
+              exit 1
+            fi
           elif [[ ${METHOD} == direct ]]; then
             # Direct download method
-            wget -O ${SOURCE}/${{ matrix.name }}.deb ${URL}
+            wget -O ${SOURCE}${{ matrix.name }}.deb ${URL}
+            # Check if any .deb files were downloaded
+            if ! ls "${SOURCE}"*.deb &> /dev/null; then
+              echo "::error::No .deb files were downloaded for ${{ matrix.name }} on ${{ matrix.arch }}" >&2
+              echo "Patterns tried: ${PATTERNS[*]}" >&2
+              exit 1
+            fi
           else
             # Aptly mirror method
             # Pin aptly state (critical in GH Actions containers)
@@ -592,17 +627,19 @@ jobs:
           fi
 
           # Repack deb files with Armbian version
-          apt-get install -y devscripts
-          DEBS=($(sudo find "${SOURCE}"* -type f -name '*firefox_*.deb'))
-          for d in "${DEBS[@]}"; do
-            BEFORE=$(deb-reversion -c ${d} -s armbian)
-            # Add epoch 9
-            AFTER=9:$(echo $BEFORE | cut -d":" -f2)
-            echo "$d : $BEFORE -> $AFTER"
-            DEBEMAIL=info@armbian.com deb-reversion -v $AFTER -s armbian $d
-            rm $d
-            mv *.deb ${SOURCE}
-          done
+          if [[ "${{ matrix.name }}" == "firefox" ]]; then
+            apt-get install -y devscripts
+            DEBS=($(sudo find "${SOURCE}"* -type f -name '*firefox_*.deb'))
+            for d in "${DEBS[@]}"; do
+              BEFORE=$(deb-reversion -c ${d} -s armbian)
+              # Add epoch 9
+              AFTER=9:$(echo $BEFORE | cut -d":" -f2)
+              echo "$d : $BEFORE -> $AFTER"
+              DEBEMAIL=info@armbian.com deb-reversion -v $AFTER -s armbian $d
+              rm $d
+              mv *.deb ${SOURCE}
+            done
+          fi
 
           # Store info to GitHub Actions
           AFTER_VERSION=$(find "$SOURCE" -type f -name "${INSTALL%% *}*.deb" -exec dpkg-deb -f {} Version \; | sort | uniq | tail -n 1 | cut -d":" -f2)
@@ -616,32 +653,19 @@ jobs:
           if [[ ${TARGET} == main ]]; then
             # Copy to main repository directories
             if grep -qE 'B' <<< "$REPOSITORY"; then
-              find $SOURCE -type f -name "*${{ matrix.arch }}.deb" -exec cp {} build/output/debs-beta/ \;
+              find $SOURCE -type f -name "*.deb" -exec cp -v {} build/output/debs-beta/ \;
             fi
             if grep -qE 'S' <<< "$REPOSITORY"; then
-              find $SOURCE -type f -name "*${{ matrix.arch }}.deb" -exec cp {} build/output/debs/ \;
+              find $SOURCE -type f -name "*.deb" -exec cp -v {} build/output/debs/ \;
             fi
-          #elif [[ ${RELEASE} == all ]]; then
-          #  # Copy to all release directories
-          #  for i in ${ALL_RELEASES[@]}; do
-          #    if grep -qE 'B' <<< "$REPOSITORY"; then
-          #      find $SOURCE -type f -name "*${{ matrix.arch }}.deb" -exec cp {} build/output/debs-beta/extra/${i}-${TARGET} \;
-          #    fi
-          #    if grep -qE 'S' <<< "$REPOSITORY"; then
-          #      find $SOURCE -type f -name "*${{ matrix.arch }}.deb" -exec cp {} build/output/debs/extra/${i}-${TARGET} \;
-          #    fi
-          #  done
           else
             # Copy to specific release directories
-            elements=($(echo $RELEASE | tr ':' "\n"))
-            for SELECTED_RELEASE in "${elements[@]}"; do
-              if grep -qE 'B' <<< "$REPOSITORY"; then
-                find $SOURCE -type f -name "*${{ matrix.arch }}.deb" -exec cp {} build/output/debs-beta/extra/${SELECTED_RELEASE}-${TARGET} \;
-              fi
-              if grep -qE 'S' <<< "$REPOSITORY"; then
-                find $SOURCE -type f -name "*${{ matrix.arch }}.deb" -exec cp {} build/output/debs/extra/${SELECTED_RELEASE}-${TARGET} \;
-              fi
-            done
+            if grep -qE 'B' <<< "$REPOSITORY"; then
+              find $SOURCE -type f -name "*.deb" -exec cp -v {} build/output/debs-beta/extra/${{ matrix.release }}-${TARGET} \;
+            fi
+            if grep -qE 'S' <<< "$REPOSITORY"; then
+              find $SOURCE -type f -name "*.deb" -exec cp -v {} build/output/debs/extra/${{ matrix.release }}-${TARGET} \;
+            fi
           fi
 
           # Generate summary table
